kind: ConfigMap
apiVersion: v1
metadata:
  name: credentials-3
  annotations:
    user1: pass1
    user3: pass3
data:
  htpasswd: |-
    user1:$apr1$Zccma78v$YWoyZwigRmYzkd5QlqDqi.
    user3:$apr1$AVHFd0Dw$2k8qQwvFk88z2UNw5UfR91
