apiVersion: v1
kind: Service
metadata:
  name: auth-url-basic
  labels:
    app: auth-url-basic
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: auth-url-basic
---
apiVersion: v1
kind: Service
metadata:
  name: auth-url-basic-extern
  labels:
    app: auth-url-basic
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: auth-url-basic
